#+TITLE: id_bot, a free (as in freedom!) discord bot
#+AUTHOR: CToID
#+OPTIONS: num:nil

Copyright (C) 2022 CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* 目錄 Table of Contents                                                :toc:
- [[#主要功能-main-features][主要功能 Main Features]]
  - [[#回覆特定字詞-replying-to-trigger-words][回覆特定字詞 Replying to Trigger Words]]
  - [[#今日運勢-todays-luck][今日運勢 Today's Luck]]
  - [[#選擇困難症剋星-choosing-things-for-you][選擇困難症剋星 Choosing Things for You]]
  - [[#透過表情符號給予身份組-choosing-roles-via-reacting-to-a-message][透過表情符號給予身份組 Choosing Roles via Reacting to a Message]]
- [[#接下來要做的-todos][接下來要做的 TODOs]]

* 主要功能 Main Features
This is basically a rewrite of bot_269, so most of the features are similar.
** 回覆特定字詞 Replying to Trigger Words
** 今日運勢 Today's Luck
** 選擇困難症剋星 Choosing Things for You
** 透過表情符號給予身份組 Choosing Roles via Reacting to a Message

* 接下來要做的 TODOs
- [ ] 優化回覆列表 Make reply list easier to read
