#+TITLE: Daily luck
#+AUTHOR: CToID
#+PROPERTY: header-args :tangle ../src/luck.py
#+OPTIONS: num:nil

Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* Table of contents :TOC_1:noexport:
- [[#the-license-notices][The license notices]]
- [[#import-packages][Import packages]]
- [[#the-daily_luck-class][The daily_luck class]]
- [[#the-luck-function][The luck function]]
- [[#setup-function][Setup function]]

* The license notices
#+begin_src python
"""
Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
#+end_src

* Import packages
| Package              | Description                   |
|----------------------+-------------------------------|
| discord              | Discord API for python        |
| discord.ext.commands | Command extension for discord |
| json                 | For storing reply datas       |
| random               | For random selection          |
| datetime             | For Checking date             |
#+begin_src python
import discord, json, random, datetime
from discord.ext import commands
#+end_src

* The daily_luck class
#+begin_src python
class daily_luck (commands.Cog):
  def __init__ (self, bot):
    self.bot = bot
#+end_src

* The luck function
 #+begin_src python
  @commands.command ()
  async def 今日運勢 (self, ctx):
    lucks = ("大凶", "凶", "小凶", "平", "小吉", "吉", "大吉", "你命由你不由天，自己幸福自己拼", "在吉跟不吉之間")
 #+end_src

** Check if the record file exists
#+begin_src python
    try:
      with open ("./datas/luck.json") as luck_file:
        records = json.load (luck_file)
    except:
      with open ("./datas/luck.json", "w") as luck_file:
        json.dump ({}, luck_file, indent = 2)
      with open ("./datas/luck.json") as luck_file:
        records = json.load (luck_file)
#+end_src

** Check if user already used this command today
If the user haven't used this command before.
Note that a time shift of 8 hours (UTC+8) is also set here. 
#+begin_src python
    shift = datetime.timedelta (hours = 8)

    if (str (ctx.author.id) not in records):
      today_luck = random.choice (lucks)
      await ctx.reply (today_luck)
      records[str (ctx.author.id)] = [(ctx.message.created_at + shift).date ().isoformat (), today_luck]
      with open ("./datas/luck.json", "w") as luck_file:
        json.dump (records, luck_file, indent = 2)
      return
#+end_src

If the user is already in the record, then check if he/she had used this command before in the same day.
#+begin_src python
    if (datetime.date.fromisoformat (records[str (ctx.author.id)][0]) < datetime.date.today ()):
      today_luck = random.choice (lucks)
      await ctx.reply (today_luck)
      records[str (ctx.author.id)] = [(ctx.message.created_at + shift).date ().isoformat (), today_luck]
      with open ("./datas/luck.json", "w") as luck_file:
        json.dump (records, luck_file, indent = 2)
    else:
      await ctx.reply (f"啊不就跟你說今天是 {records[str (ctx.author.id)][1]} 了")
#+end_src

* Setup function
#+begin_src python
def setup (bot):
  bot.add_cog (daily_luck (bot))
#+end_src
