#+TITLE: Replying to specified message
#+AUTHOR: CToID
#+PROPERTY: header-args :tangle ../src/reply.py
#+OPTIONS: num:nil

Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* Table of contents :TOC_1:noexport:
- [[#the-license-notice][The License Notice]]
- [[#import-packages][Import Packages]]
- [[#define-reply-class-and-init][Define Reply Class and Init]]
- [[#function-for-making-reply-list][Function for Making Reply List]]
- [[#reply-function][Reply Function]]
- [[#setup][Setup]]

* The License Notice
#+begin_src python
"""
Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
#+end_src

* Import Packages
#+begin_src python
import discord, json, os, asyncio, math
from discord import ui
from discord.ext import commands
#+end_src

* Define Reply Class and Init
#+begin_src python
class reply (commands.Cog):
  def __init__ (self, bot):
    self.bot = bot
#+end_src

* Function for Making Reply List
This function will take the list of reply, and make it into separate pages of embed messages.
#+begin_src python
  async def reply_pages (self, ctx, list_rp):
#+end_src
** Variables
#+begin_src python
    list_rp = list (list_rp.items ())
    per_page = 10
    pages = math.ceil (len (list_rp) / per_page)
    cur_page = 1
    pages_index = {}
    pages_embeds = {}
#+end_src

** Turn Reply List into Embed Messages
#+begin_src python
    for i in range (pages):
      pages_index[f"page_{i + 1}"] = list_rp[i * 10:(i + 1) * 10]

    pages_index = list (pages_index.items ())

    for i in range (pages):
      pages_embeds[f"page_{i + 1}"] = discord.Embed (title = f"{ctx.guild.name}'s Reply List").set_footer (text = f"Page {i + 1} / {pages}")
      for j in range (len (pages_index[i][1])):
        name = pages_index[i][1][j][0]
        value = pages_index[i][1][j][1]
        pages_embeds[f"page_{i + 1}"].add_field (name = name, value = f"╰ {value}", inline = False)
#+end_src

** A Function to Create View
#+begin_src python
    def create_view (n_but, p_but):
      view = ui.View ()
      n_button = ui.Button (label = "Next Page", disabled = n_but)
      p_button = ui.Button (label = "Previous Page", disabled = p_but)
      n_button.callback = next_page 
      p_button.callback = previous_page 
      view.add_item (p_button)
      view.add_item (n_button)
      return view
#+end_src

** Callback Function for Next Page Button
#+begin_src python
    async def next_page (interactive):
      await interactive.response.defer ()
      nonlocal cur_page
      if (cur_page != pages):
        cur_page += 1
        await msg.edit (embed = pages_embeds[f"page_{cur_page}"], view = create_view (False, False))
        if (cur_page == pages):
          await msg.edit (embed = pages_embeds[f"page_{cur_page}"], view = create_view (True, False))
#+end_src

** Callback Function for Previous Page Button
#+begin_src python
    async def previous_page (interactive):
      await interactive.response.defer ()
      nonlocal cur_page
      if (cur_page > 1):
        cur_page -= 1
        await msg.edit (embed = pages_embeds[f"page_{cur_page}"], view = create_view (False, False))
        if (cur_page == 1):
          await msg.edit (embed = pages_embeds[f"page_{cur_page}"], view = create_view (False, True))
#+end_src

** Send the First Page
#+begin_src python
    if pages == 1:
      view = create_view (True, True)
    else:
      view = create_view (False, True)
    msg = await ctx.send (embed = pages_embeds[f"page_{cur_page}"], view = view)
#+end_src

** A Loop
#+begin_src python
    while True:
      try:
        user = await self.bot.wait_for ("interaction", timeout = 25.0,
                                        check = lambda interaction: interaction.user == ctx.author)
      except asyncio.TimeoutError:
        await msg.edit (embed = pages_embeds[f"page_{cur_page}"], view = create_view (True, True))
        break
#+end_src

* Reply Function
#+begin_src python
  @commands.command ()
  async def reply (self, ctx, key, content_1 = None, content_2 = None):
#+end_src

** Open the Reply Datas File
#+begin_src python
    try:
      with open (f"./datas/reply/reply_{ctx.guild.id}.json", encoding = "utf8") as reply_file:
        rp = json.load (reply_file)
    except:
      with open (f"./datas/reply/reply_{ctx.guild.id}.json", "w", encoding = "utf8") as reply_file:
        json.dump ({}, reply_file, ensure_ascii = False)
        rp = json.load (reply_file)
#+end_src

** Add
#+begin_src python
    if (key == "add"):
      try:
        if ((content_1 == None)
            or ((content_2 == None) and (len (ctx.message.attachments) == 0))):
          await ctx.send ("你什麼都沒有給我是要加什麼啦")
          return
        elif (len (ctx.message.attachments) != 0):
          urls = []
          for i in ctx.message.attachments:
            urls.append (i.url)
          rp[content_1] = urls
        else:
          rp[content_1] = content_2
        await ctx.reply (f"以後有人說 {content_1}，我會回他 {content_2}")
      except:
        return
#+end_src

** Delete
#+begin_src python
    elif (key == "del"):
      if (content_1 == None):
        await ctx.send ("你什麼都沒有給我是要刪空氣喔")
        return
      else:
        try:
          rp.pop (content_1)
          await ctx.send (f"刪除了 {content_1}")
        except:
          await ctx.send ("本來就沒有的東西我要怎麼刪")
          return
#+end_src

** Send Reply Data File
#+begin_src python
    elif (key == "list_f"):
      await ctx.send (file = discord.File (f"./datas/reply/reply_{ctx.guild.id}.json"))
      return
#+end_src

** Send Reply Data in Embed Messages
#+begin_src python
    elif (key == "list"):
      list_rp = rp.copy ()
      if len (list_rp) == 0:
        await ctx.send ("好像還沒有半個回覆")
        return
      for i in list_rp:
        if ((type (list_rp[i]) == list) or (list_rp[i].startswith ("http"))):
          list_rp[i] = "<This is an image or video>"
      for i in list_rp:
        words = "\n".join ([i, f"└ {list_rp[i]}\n"])
      await reply.reply_pages (self, ctx, list_rp)
#+end_src

** Return if None of Above
#+begin_src python
    else:
      return
#+end_src

** Write Changes
#+begin_src python
    with open (f"./datas/reply/reply_{ctx.guild.id}.json", "w", encoding = "utf8") as reply_file:
      json.dump (rp, reply_file, indent = 2, ensure_ascii = False)
#+end_src

* Setup
#+begin_src python
async def setup (bot):
  await bot.add_cog (reply (bot))
#+end_src
