#+TITLE: Selection
#+AUTHOR: CToID
#+PROPERTY: header-args :tangle ../src/select.py
#+OPTIONS: num:nil

Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* Table of contents :toc_1:noexport:
- [[#the-license-notice][The license notice]]
- [[#import-packages][Import packages]]
- [[#define-select-class][Define select class]]
- [[#setup-function][Setup function]]

* The license notice
#+begin_src python
"""
Copyright (C) 2022  CToID

This file is part of id_bot

id_bot is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

id_bot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
#+end_src

* Import packages
| Package              | Description                  |
|----------------------+------------------------------|
| dicord               | Discord API for python       |
| discord.ext.commands | Commands support for discord |
| random               | For choosing things          |
#+begin_src python
import discord, random
from discord.ext import commands
#+end_src

* Define select class
#+begin_src python
class select (commands.Cog):
  def __init__ (self, bot):
    self.bot = bot
#+end_src

** Selection command
#+begin_src python
  @commands.command ()
  async def sel (self, ctx, *items):
    item = random.choice (items)
    await ctx.reply (f"我選 {item}")
#+end_src

* Setup function
#+begin_src python
async def setup (bot):
  await bot.add_cog (select (bot))
#+end_src
