#+TITLE: id_bot使用說明
#+AUTHOR: CToID

* 目錄 :toc:noexport:
- [[#回覆][回覆]]
  - [[#新增回覆][新增回覆]]
  - [[#刪除回覆][刪除回覆]]
  - [[#列出回覆][列出回覆]]
- [[#運勢][運勢]]
- [[#身份組選擇][身份組選擇]]
  - [[#範例][範例]]

* 回覆
讓機器人針對特定的內容做回覆吧。

** 新增回覆
~id reply add <觸發字> <回覆內容>~

可用來新增要機器人回覆的語句等。
如果觸發字或回覆內容中含有空格，請用雙引號(")括起來。

*** 範例：
假設現在要機器人在有人說「你到底」的時候回應「有什麼問題」

~id reply add 你到底 有什麼問題~

假設現在要機器人在有人說「ad astra」的時候回應「per aspera」

~id reply add "ad astra" "per aspera"~

** 刪除回覆
~id reply del <觸發字>~ 

用來將新增過的回覆刪除。

*** 範例
假設現在要機器人刪掉剛剛的第一個範例新增的回覆

~id reply del 你到底~

假設現在要機器人刪掉剛剛的第二個範例新增的回覆

~id reply del "ad astra"~

** 列出回覆
~id reply list~ 

用來看現在所有的回覆。

* 運勢
~id 今日運勢~ 

問看看機器人今天的運氣怎麼樣。

* 身份組選擇
~id role_select <訊息網址或id> <表情符號1> <@表情符號1拿到的身份組1> <@表情符號1拿到的身份組2>...(身份組間以空格格開) <表情符號2> <@表情符號2拿到的身份組1> <@表情符號2拿到的身份組2>...(身份組間以空格格開)~ 

讓伺服器成員用按特定訊息下的表情符號來取得身份組。
*只有有管理身份組權限的人可以使用。*

** 範例
假設現在你要幫按🤔的人新增 @身份組一 和 @身份組二 ，按🐧的人新增 @身份組三 、 @身份組四 和 @身份組五 ，按😂的人新增 @身份組六。

然後你的訊息連結是https://discord.com/channels/967880009186435083/967880010281123913/992768436939788358

訊息連結可以透過在該訊息上按右鍵來獲取，或你也可以提供給機器人你的訊息ID，一樣可以右鍵獲取，不過要先去Discord設定中打開開發者模式。

~id role_select https://discord.com/channels/967880009186435083/967880010281123913/992768436939788358 🤔 @身份組一 @身份組二 🐧 @身份組三 @身份組四 @身份組五 😂 @身份組六~
